name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@11310527b429536e263dc6cc47873e608189ba21
